# Generated by Django 2.0 on 2018-02-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('popularity_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('cmc_rank', models.FloatField(blank=True, default=0.0, null=True)),
                ('circulating_supply', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_supply', models.FloatField(blank=True, default=0.0, null=True)),
                ('trading_volume', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_history',
            },
        ),
        migrations.CreateModel(
            name='AssetMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('social', 'Social'), ('news', 'News')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('sentiment_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('backlinks_count', models.FloatField(blank=True, default=0.0, null=True)),
                ('scam_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('fud_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_media',
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('coin', 'Coin'), ('token', 'Token')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('volume', models.FloatField(blank=True, default=0.0, null=True)),
                ('circulating_supply', models.FloatField(blank=True, default=0.0, null=True)),
                ('latest_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='AssetVoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('put', 'PUT'), ('call', 'CALL')], max_length=255)),
                ('sentiment', models.CharField(choices=[('bearish', 'Bearish'), ('bullish', 'Bullish')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_vote',
            },
        ),
        migrations.CreateModel(
            name='MarketAssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('latest_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_asset',
            },
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('market_type', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(max_length=255)),
                ('trade_volume', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='MediaReactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('scam', 'Scam'), ('fud', 'FUD'), ('fake', 'Fake')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reactions', to='assets.AssetMediaModel')),
            ],
            options={
                'db_table': 'media_reaction',
            },
        ),
        migrations.CreateModel(
            name='PriceFutureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('price_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_price_futures', to='assets.AssetModel')),
            ],
            options={
                'db_table': 'price_future',
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('price_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_price_histories', to='assets.AssetModel')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
    ]
