# Generated by Django 2.0 on 2018-02-18 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediareactionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketassetmodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_markets',
                                    to='assets.AssetModel'),
        ),
        migrations.AddField(
            model_name='marketassetmodel',
            name='exchange_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='assets.AssetModel'),
        ),
        migrations.AddField(
            model_name='marketassetmodel',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_assets',
                                    to='assets.MarketModel'),
        ),
        migrations.AddField(
            model_name='assetvotemodel',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='asset_votes', to='assets.AssetModel'),
        ),
        migrations.AddField(
            model_name='assetvotemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assets', to='company.CompanyModel'),
        ),
        migrations.AddField(
            model_name='assetmediamodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias',
                                    to='assets.AssetModel'),
        ),
        migrations.AddField(
            model_name='assethistorymodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_histories',
                                    to='assets.AssetModel'),
        ),
    ]
