# Generated by Django 2.0 on 2018-03-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0005_auto_20180302_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistorymodel',
            name='market_capital',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
