# Generated by Django 2.0 on 2018-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180302_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmediamodel',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
