# Generated by Django 2.0 on 2018-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180302_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
