# Generated by Django 2.0 on 2018-03-04 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0010_auto_20180302_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assethistorymodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetmediamodel',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'ordering': ['-cmc_id']},
        ),
        migrations.AlterModelOptions(
            name='assetvotemodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='domainmediamodel',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='marketassetmodel',
            options={'ordering': ['-volume']},
        ),
        migrations.AlterModelOptions(
            name='marketmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mediareactionmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricefuturemodel',
            options={'ordering': ['price_at']},
        ),
        migrations.AlterModelOptions(
            name='pricehistorymodel',
            options={'ordering': ['-price_at']},
        ),
    ]
